/**
 * EquiGen brand system.
 *
 * Single source of truth for every user-facing brand string, colour token and
 * legal-disclaimer default that appears in exported artifacts (PDF, HTML, Excel)
 * or in product metadata.
 *
 * Every exportable artifact is white-label: a multi-tenant `Organization` may
 * override the firm identity. Resolution order is always
 *   org override -> process env -> these neutral platform defaults
 *
 * IMPORTANT: the disclaimer defaults are deliberately NEUTRAL placeholders, not
 * claims about a real entity. A research report carries a SEBI (Research
 * Analysts) Regulations, 2014 certification, so the publishing firm identity must
 * always come from the tenant. Callers must pass `orgName`; if it is absent the
 * platform renders an explicit "unconfigured" marker rather than asserting a
 * registration that may not exist.
 */

export interface BrandIdentity {
  /** Platform/product wordmark. */
  productName: string;
  /** Human-facing platform description used in report footers. */
  productDescriptor: string;
  /** Default publishing-firm name. Placeholder only — override per tenant. */
  defaultOrgName: string;
  /** Default compliance/grievance contact. Placeholder only — override per tenant. */
  defaultComplianceEmail: string;
  /** Default public website. Placeholder only — override per tenant. */
  defaultWebsite: string;
}

export const BRAND: BrandIdentity = {
  productName: "EquiGen",
  productDescriptor: "EquiGen Institutional Research",
  defaultOrgName: "",
  defaultComplianceEmail: "",
  defaultWebsite: "",
};

/** Marker rendered when a tenant has not configured its publishing identity. */
export const UNCONFIGURED_FIRM_MARKER = "[Firm identity not configured]";

/** Palette for published research artifacts (PDF / HTML / Excel). */
export const BRAND_COLORS = {
  /** Deep navy — primary headings, cover band. */
  primary: "#0B3C5D",
  /** Teal — rules, table accents, chart bars. */
  secondary: "#07877B",
  /** Amber — highlights, trend lines, the wordmark accent. */
  accent: "#D9B310",
  darkText: "#1D2731",
  lightBg: "#F9F9F9",
  border: "#E8E8E8",
  buyRating: "#28A745",
  sellRating: "#DC3545",
  holdRating: "#FFC107",
} as const;

export type BrandColor = keyof typeof BRAND_COLORS;

/** Resolved firm identity for one export. */
export interface ResolvedFirmIdentity {
  orgName: string;
  complianceEmail: string;
  website: string;
  /** True when the firm identity was never configured — callers must surface this. */
  isUnconfigured: boolean;
}

/**
 * Resolves the publishing-firm identity for an export, honouring tenant overrides
 * then env, and flagging the case where no real firm identity was supplied.
 *
 * A report that carries a SEBI certification must never silently attribute itself
 * to a made-up firm, so an unconfigured identity is returned explicitly rather
 * than being defaulted to a plausible-looking name.
 */
export function resolveFirmIdentity(
  overrides: Partial<Pick<ResolvedFirmIdentity, "orgName" | "complianceEmail" | "website">> = {},
  env: Record<string, string | undefined> = process.env,
): ResolvedFirmIdentity {
  const orgName = (overrides.orgName ?? env.EQUIGEN_DEFAULT_ORG_NAME ?? "").trim();
  const complianceEmail = (
    overrides.complianceEmail ??
    env.EQUIGEN_DEFAULT_COMPLIANCE_EMAIL ??
    ""
  ).trim();
  const website = (overrides.website ?? env.EQUIGEN_DEFAULT_WEBSITE ?? "").trim();

  return {
    orgName: orgName || UNCONFIGURED_FIRM_MARKER,
    complianceEmail,
    website,
    isUnconfigured: orgName.length === 0,
  };
}

/** SEBI-mandated risk warning. Verbatim statutory text — never paraphrase. */
export const SEBI_RISK_WARNING =
  "Investment in securities market are subject to market risks. Read all the related documents carefully before investing.";

/** Marks a note as an unreviewed AI draft. Rendered on every non-attested export. */
export function draftWatermark(generatedBy: string = BRAND.productName): string {
  return `This report was generated by ${generatedBy} AI and has not been reviewed by a SEBI-registered Research Analyst. It does not constitute investment advice.`;
}