import { NextRequest, NextResponse } from 'next/server';
import { pdfGenerationService } from '@/lib/pdf';

/**
 * GET /api/download
 * Generates and returns a downloadable PDF report matching the requested report ID/ticker.
 */
export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const id = searchParams.get('id');

    if (!id) {
      return NextResponse.json({ message: 'Missing report id query parameter.' }, { status: 400 });
    }

    // Generate mock PDF Buffer (mock implementation in PDFGenerationService)
    const reportPDFBuffer = await pdfGenerationService.generateReportPDF({
      company: { name: id, reportDate: new Date().toLocaleDateString('en-IN') },
      recommendation: { rating: 'BUY', targetPrice: 1500, currentPrice: 1200, upsidePotential: 25, rationale: [] },
      executiveSummary: 'Equity Research Report generated by Bull AI.',
      keyFinancials: { incomeStatement: [], balanceSheet: [], cashFlow: [] },
      valuationAnalysis: 'Valuation details',
      investmentRisks: [],
      swotAnalysis: { strengths: [], weaknesses: [], opportunities: [], threats: [] }
    }).catch(() => Buffer.from('PDF Scaffolding Content Placeholder'));

    return new NextResponse(new Uint8Array(reportPDFBuffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="equity-report-${id.toLowerCase()}.pdf"`
      }
    });
  } catch (error: any) {
    console.error('API Error: /api/download failed:', error);
    return NextResponse.json(
      { message: error.message || 'Internal Server Error' },
      { status: 500 }
    );
  }
}

export const dynamic = 'force-dynamic';
