import Link from "next/link";
import { ArrowLeft, BarChart3 } from "lucide-react";

export const metadata = {
  title: "Terms of Service — EquiGen",
  description: "Terms governing use of the EquiGen institutional equity research terminal.",
};

const SECTIONS = [
  {
    id: "acceptance",
    heading: "1. Acceptance",
    body: [
      "By creating an account or using the EquiGen Research Terminal (\"the Service\") you agree to these terms on behalf of yourself and the organization you represent. If you do not agree, do not use the Service.",
      "You must be legally capable of entering into this agreement and, where your organization is subscribing, you must hold authority to bind that organization to a paid plan.",
    ],
  },
  {
    id: "permitted-use",
    heading: "2. Permitted Use",
    body: [
      "The Service is licensed per organization. Seats may be shared among named analysts of your organization but credentials may not be resold, sublicensed, or used to build a competing offering.",
      "You may upload only documents you are licensed to process: annual reports, filings, investor presentations, earnings transcripts, and equivalent public or licensed material. You may not upload client-confidential or MNPI material you are not authorised to process.",
    ],
  },
  {
    id: "research-output",
    heading: "3. Research Output Is Not Advice",
    body: [
      "Notes, price targets, valuations, and models produced by the Service are decision-support output generated by automated systems. They are not investment advice, an offer, or a solicitation to buy or sell any security.",
      "Outputs may contain extraction or modelling errors. You are responsible for reviewing every figure, assumption, and conclusion before relying on it, and for complying with your firm's own research and compliance policies.",
    ],
  },
  {
    id: "billing",
    heading: "4. Plans, Billing and Cancellation",
    body: [
      "Plans are billed per organization, not per user, and quotas are shared across every seat. Prices are shown in Indian Rupees and charged via Dodo Payments, which acts as our merchant of record and collects taxes on our behalf.",
      "Paid subscriptions renew automatically each cycle until cancelled. You may cancel at any time; cancellation takes effect at the close of the current billing period and the organization reverts to the Free plan with its then-current quota.",
      "Refunds are discretionary and, where granted, are issued by our merchant of record to the original payment method. Usage consumed before cancellation is non-refundable except where required by law.",
    ],
  },
  {
    id: "availability",
    heading: "5. Availability and Changes",
    body: [
      "We aim for high availability but do not guarantee uninterrupted service. Quotas, plan features, and prices may change with reasonable notice to paying organizations.",
      "Plan quotas reset at the start of each calendar month (UTC).",
    ],
  },
  {
    id: "termination",
    heading: "6. Suspension and Termination",
    body: [
      "We may suspend an account that breaches these terms, attempts to circumvent plan quotas, probes the Service for vulnerabilities without authorisation, or unlawfully infringes third-party rights.",
      "You may delete your organization at any time. We may retain de-identified usage records where required for legal, tax, or regulatory obligations.",
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="auth-theme relative min-h-screen w-full flex flex-col bg-[#F6F4EE] text-[#1A1917] antialiased font-sans">
      <div className="absolute inset-0 z-0 overflow-hidden pointer-events-none">
        <div className="absolute inset-0 bg-[radial-gradient(#D8D4C9_1px,transparent_1px)] [background-size:26px_26px] opacity-[0.35]" />
        <div className="absolute w-[520px] h-[520px] rounded-full bg-amber-300/25 blur-[130px] -top-40 -left-28" />
      </div>

      <header className="relative z-10 h-[68px] w-full bg-white border-b border-[#E3DFD5] px-5 sm:px-6 flex items-center justify-between shrink-0 shadow-2xs">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-[#1A1917] flex items-center justify-center shadow-xs">
            <BarChart3 className="w-5 h-5 text-white stroke-[2.5]" />
          </div>
          <div className="flex items-center gap-1.5">
            <span className="text-base font-extrabold tracking-tight text-[#1A1917]">EquiGen</span>
            <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-[#F1EFEA] text-[#7A7569] border border-[#E3DFD5] tracking-wider uppercase">
              Pro
            </span>
          </div>
        </div>
        <Link
          href="/"
          className="h-9 px-3.5 flex items-center gap-1.5 bg-white border border-[#E0DCD3] rounded-xl text-[11px] font-bold text-[#1A1917] hover:bg-[#FAF8F5] hover:border-[#D5D0C3] transition-all duration-200"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          Back
        </Link>
      </header>

      <main className="relative z-10 flex-1 w-full flex flex-col items-center px-4 py-10 sm:py-14">
        <article className="w-full max-w-3xl bg-white border border-[#E3DFD5] rounded-3xl p-6 sm:p-9 shadow-xs animate-fadeIn">
          <span className="inline-flex items-center gap-1.5 px-3 py-1 bg-[#F1EFEA] border border-[#E3DFD5] rounded-full text-[10px] font-bold uppercase tracking-wider text-[#6E695E] mb-3">
            Legal
          </span>
          <h1 className="text-3xl font-extrabold tracking-tight text-[#1A1917]">
            Terms of <span className="text-amber-600">Service</span>
          </h1>
          <p className="text-[11px] text-[#8C877D] font-medium mt-2 mb-8">
            Last updated {new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}
          </p>

          <div className="space-y-8">
            {SECTIONS.map((section) => (
              <section key={section.id} id={section.id} className="scroll-mt-24">
                <h2 className="text-sm font-extrabold text-[#1A1917] mb-2.5">{section.heading}</h2>
                <div className="space-y-2.5">
                  {section.body.map((paragraph) => (
                    <p key={paragraph} className="text-xs text-[#59554A] leading-relaxed">
                      {paragraph}
                    </p>
                  ))}
                </div>
              </section>
            ))}

            <section id="disclosures" className="scroll-mt-24 pt-6 border-t border-[#EAE6DE]">
              <h2 className="text-sm font-extrabold text-[#1A1917] mb-2.5">Statutory Disclosures</h2>
              <div className="space-y-2.5">
                <p className="text-xs text-[#59554A] leading-relaxed">
                  EquiGen is a research productivity tool. It is not a SEBI-registered investment
                  adviser, research analyst, or broker, and it does not receive trade-brokerage
                  commissions or third-party distribution incentives.
                </p>
                <p className="text-xs text-[#59554A] leading-relaxed">
                  Users who publish research under a SEBI Research Analyst registration remain
                  responsible for their own disclosures, disclaimers, and record-keeping. EquiGen
                  records the registration number supplied by the user against notes they sign off,
                  but does not verify its validity with SEBI.
                </p>
                <p className="text-xs text-[#59554A] leading-relaxed">
                  Market and reference data surfaced by the Service is sourced from public filings
                  and third-party providers and may be delayed, incomplete, or restated. Nothing in
                  the Service constitutes investment advice or a personal recommendation.
                </p>
              </div>
            </section>
          </div>

          <div className="mt-8 pt-6 border-t border-[#EAE6DE] flex flex-wrap items-center gap-x-5 gap-y-2 text-[11px] text-[#7A7569] font-medium">
            <Link href="/privacy" className="text-[#1A1917] font-bold underline underline-offset-2 decoration-amber-500 decoration-2 hover:decoration-[#1A1917]">
              Privacy Policy
            </Link>
            <Link href="/" className="text-[#1A1917] font-bold underline underline-offset-2 decoration-amber-500 decoration-2 hover:decoration-[#1A1917]">
              Back to EquiGen
            </Link>
          </div>
        </article>
      </main>

      <footer className="relative z-10 w-full px-4 py-4 text-center text-[10px] text-[#9C978B] font-medium border-t border-[#E3DFD5]">
        EquiGen Research Terminal · For institutional use only · Research is not investment advice
      </footer>
    </div>
  );
}
