import { NextRequest, NextResponse } from "next/server";
import { masterPlannerAgent } from "@/lib/ai/planner/master-planner";
import { getAuthSession, requireApiSecret } from "@/lib/utils/auth";
import { ResearchGoal, ResearchPlanRecord } from "@/types/plan4";
import { prisma } from "@/lib/db";

/**
 * POST /api/agent/plan
 * Creates a new research plan from a natural-language goal.
 * Body: { goalText, ticker, companyName, depth, sessionId, isin? }
 */
export async function POST(req: NextRequest) {
  const authError = requireApiSecret(req);
  if (authError) return authError;

  try {
    const body = await req.json();
    const { goalText, ticker, companyName, depth, sessionId, isin } = body as Partial<ResearchGoal>;

    if (!goalText || !ticker || !companyName || !sessionId) {
      return NextResponse.json(
        { message: "goalText, ticker, companyName, and sessionId are required." },
        { status: 400 }
      );
    }

    const authSession = getAuthSession(req);
    const userId = authSession?.userId || "analyst";
    const orgId = authSession?.orgId || "default-org";

    // Ensure ResearchSession exists (create on demand if auto-generated by UI)
    let session = await prisma.researchSession.findUnique({
      where: { id: sessionId },
      select: { orgId: true },
    });

    if (!session) {
      session = await prisma.researchSession.create({
        data: {
          id: sessionId,
          reportId: "report_plan_" + Date.now(),
          orgId: orgId,
          createdBy: userId,
        },
        select: { orgId: true },
      });
    }

    const apiKeyRecord = await prisma.apiKey.findFirst({
      where: { orgId: session.orgId ?? "default-org", provider: "groq" },
    });

    const apiKey = apiKeyRecord?.encryptedKey ?? process.env.GROQ_API_KEY ?? "";

    const goal: ResearchGoal = {
      goalText,
      ticker: ticker.toUpperCase(),
      companyName,
      depth: depth ?? "standard",
      sessionId,
      isin,
    };

    const plan = await masterPlannerAgent.createPlan(goal, apiKey);

    return NextResponse.json({ success: true, plan });
  } catch (error: unknown) {
    console.error("[/api/agent/plan POST] Error:", error);
    const msg = error instanceof Error ? error.message : "Internal Server Error";
    return NextResponse.json({ message: msg }, { status: 500 });
  }
}

/**
 * GET /api/agent/plan?planId=X
 * Retrieves a specific research plan, or lists all research plans if planId is omitted.
 */
export async function GET(req: NextRequest) {
  const authError = requireApiSecret(req);
  if (authError) return authError;

  try {
    const rawPlanId = req.nextUrl.searchParams.get("planId") || req.nextUrl.searchParams.get("id");

    if (rawPlanId) {
      const cleanPlanId = rawPlanId.replace(/^rep_/, "");
      let plan = await masterPlannerAgent.getPlan(cleanPlanId) || await masterPlannerAgent.getPlan(rawPlanId);

      // Also look up in ReportHistory (covers standalone manual uploads, completed autonomous reports, etc.)
      const report = await prisma.reportHistory.findFirst({
        where: {
          OR: [
            { id: rawPlanId },
            { id: cleanPlanId },
            { id: `rep_${cleanPlanId}` },
          ],
        },
        select: {
          id: true,
          companyName: true,
          status: true,
          reportData: true,
          createdAt: true,
        },
      }).catch(() => null);

      // If plan wasn't directly found, check if the report links to a planId
      if (!plan && report) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const linkedPlanId = (report.reportData as any)?.planId;
        if (linkedPlanId) {
          plan = await masterPlannerAgent.getPlan(linkedPlanId);
        }
      }

      // If neither plan nor report exists in database, return 404
      if (!plan && !report) {
        return NextResponse.json({ message: "Plan not found." }, { status: 404 });
      }

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const sections = (report?.reportData as any)?.sections ?? null;

      // If this is a historical report without a researchPlan entry, construct a synthetic plan record
      if (!plan && report) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const repData = report.reportData as any;
        const comp = report.companyName || repData?.companyName || "Target Company";
        const tick = repData?.ticker || (comp.length <= 8 ? comp.replace(/[^a-zA-Z0-9]/g, "").toUpperCase() : comp.substring(0, 4).toUpperCase());

        const syntheticPlan: ResearchPlanRecord = {
          id: report.id,
          sessionId: "session-history",
          goalText: `Initiation of coverage on ${comp} — institutional equity research report`,
          companyName: comp,
          ticker: tick,
          milestones: [
            {
              id: "m_fetch",
              type: "fetch_documents",
              label: "Fetch Company Filings",
              description: "BSE/NSE audited filings",
              agentType: "document",
              estimatedMinutes: 3,
              estimatedCostUsd: 0.15,
              status: "completed",
              config: { sourceTypes: ["annual_report", "quarterly_results"], yearsBack: 4 },
            },
            {
              id: "m_extract",
              type: "extract_financials",
              label: "Extract Financial Data",
              description: "Audited financial statements",
              agentType: "document",
              estimatedMinutes: 2,
              estimatedCostUsd: 0.15,
              status: "completed",
              config: { fieldsToExtract: ["revenue", "ebitda", "pat"], fiscalYears: ["FY24", "FY25"] },
            },
            {
              id: "m_model",
              type: "build_financial_model",
              label: "Build Financial Model",
              description: "DCF & financial model",
              agentType: "modeling",
              estimatedMinutes: 2,
              estimatedCostUsd: 0.2,
              status: "completed",
              config: { modelType: "dcf", projectionYears: 5, runMonteCarlo: false, runSensitivity: true },
            },
            {
              id: "m_peer",
              type: "peer_benchmark",
              label: "Peer Benchmarking",
              description: "Sector multiples & peer analysis",
              agentType: "market_intel",
              estimatedMinutes: 2,
              estimatedCostUsd: 0.15,
              status: "completed",
              config: { peerTickers: [], metrics: ["pe", "ev_ebitda"] },
            },
            {
              id: "m_synthesise",
              type: "synthesise",
              label: "Synthesise Research Report",
              description: "Report synthesis & thesis",
              agentType: "synthesis",
              estimatedMinutes: 3,
              estimatedCostUsd: 0.35,
              status: "completed",
              config: { sections: ["executive_summary", "business_description", "financial_analysis", "valuation"] },
            },
            {
              id: "m_compliance",
              type: "compliance_audit",
              label: "SEBI Compliance Audit",
              description: "SEBI RA 2014 regulatory audit",
              agentType: "compliance",
              estimatedMinutes: 2,
              estimatedCostUsd: 0.15,
              status: "completed",
              config: { checkSEBIRules: true, checkMathAudit: true, checkWatermark: true },
            },
          ],
          depth: "standard",
          costEstimate: 0,
          latencyEstS: 0,
          status: "completed",
          approvedBy: "system",
          approvedAt: report.createdAt.toISOString(),
          createdAt: report.createdAt.toISOString(),
        };

        return NextResponse.json({ success: true, plan: syntheticPlan, sections });
      }

      return NextResponse.json({ success: true, plan, sections });
    }

    const authSession = getAuthSession(req);
    const userId = authSession?.userId;

    const whereClause = userId && userId !== "system-test-user"
      ? { session: { createdBy: userId } }
      : {};

    // List research plans scoped to user
    const plans = await prisma.researchPlan.findMany({
      where: whereClause,
      orderBy: { createdAt: "desc" },
      take: 50,
    });

    return NextResponse.json({ success: true, plans });
  } catch (error: unknown) {
    console.error("[/api/agent/plan GET] Error:", error);
    const msg = error instanceof Error ? error.message : "Internal Server Error";
    return NextResponse.json({ message: msg }, { status: 500 });
  }
}

/**
 * DELETE /api/agent/plan?planId=X
 * Deletes a research plan and associated runs/steering events.
 */
export async function DELETE(req: NextRequest) {
  const authError = requireApiSecret(req);
  if (authError) return authError;

  try {
    const planId = req.nextUrl.searchParams.get("planId");
    if (!planId) {
      return NextResponse.json({ message: "planId query parameter is required." }, { status: 400 });
    }

    const { count } = await prisma.researchPlan.deleteMany({
      where: { id: planId },
    });

    return NextResponse.json({ success: true, deletedPlanId: planId, count });
  } catch (error: unknown) {
    console.error("[/api/agent/plan DELETE] Error:", error);
    const msg = error instanceof Error ? error.message : "Internal Server Error";
    return NextResponse.json({ message: msg }, { status: 500 });
  }
}

export const dynamic = "force-dynamic";
