import { Annotation, StateGraph, START, END } from '@langchain/langgraph';
import { ChatGroq } from '@langchain/groq';
import { ChatOpenAI } from '@langchain/openai';
import { BaseChatModel } from '@langchain/core/language_models/chat_models';
import { z } from 'zod';
import { AIServiceOptions } from './langchain-service';
import { AIExtractionResult } from './schema';

// --- Helper: Simple Character Chunker with overlap ---

function splitTextIntoChunks(text: string, chunkSize = 20000, overlap = 2000): string[] {
  const chunks: string[] = [];
  let start = 0;
  while (start < text.length) {
    const end = Math.min(start + chunkSize, text.length);
    chunks.push(text.substring(start, end));
    start += chunkSize - overlap;
    if (end === text.length) break;
  }
  return chunks;
}

// --- Specialized Node Zod Sub-schemas ---

export const LocalExtractionSchema = z.object({
  relevantSWOT: z.array(z.string()).describe('SWOT factors or risk signals found in this section (empty if none)'),
  relevantFinancials: z.array(z.string()).describe('Key financial figures, EBITDA, revenues, or targets mentioned in this section (empty if none)'),
  briefSectionSummary: z.string().describe('1-2 sentence high-density summary of operational facts in this section')
});

export const CompanyGeneralSchema = z.object({
  companyName: z.string().describe('Full corporate name of the target entity'),
  ticker: z.string().describe('Stock market ticker symbol'),
  narrativeSummary: z.string().describe('Narrative summary of findings (outlook, recommendation, key drivers)'),
  industryOverview: z.string().describe('High-level outlook of the industry vertical'),
  businessOverview: z.string().describe('Brief operational overview of business divisions')
});

export const SwotAndThesisSchema = z.object({
  highlights: z.array(z.string()).describe('Key highlights (strengths, expansion, strategic positioning)'),
  investmentThesis: z.string().describe('Main investment case and rationale'),
  risks: z.array(z.string()).describe('Primary business and financial risks/weaknesses'),
  futureGrowth: z.string().describe('Key growth drivers and pipeline plans')
});

export const FinancialsSchema = z.object({
  revenue: z.array(z.object({
    period: z.string().describe('Fiscal period, e.g. FY23, FY24, FY25'),
    value: z.number().describe('Revenue figure value'),
    unit: z.string().describe('Cr or Mn')
  })).describe('Revenue statement entries'),
  ebitda: z.array(z.object({
    period: z.string().describe('Fiscal period'),
    value: z.number().describe('EBITDA value'),
    unit: z.string().describe('Cr or Mn')
  })).describe('EBITDA statement entries'),
  pat: z.array(z.object({
    period: z.string().describe('Fiscal period'),
    value: z.number().describe('PAT value'),
    unit: z.string().describe('Cr or Mn')
  })).describe('PAT/Net Profit statement entries'),
  currentPrice: z.number().describe('Current market stock trading price'),
  targetPrice: z.number().describe('Stock price target recommendation'),
  recommendation: z.enum(['BUY', 'HOLD', 'ACCUMULATE', 'REDUCE', 'SELL']).describe('Investment rating')
});

// --- State Definition ---

export const ResearchState = Annotation.Root({
  rawText: Annotation<string>(),
  companyName: Annotation<string>(),
  modelOptions: Annotation<AIServiceOptions>(),
  
  // Condensed summary generated by map-reduce preprocessor
  condensedContext: Annotation<string>({
    reducer: (a, b) => b,
    default: () => ''
  }),

  // Extract results
  companyGeneral: Annotation<z.infer<typeof CompanyGeneralSchema>>(),
  swotAndThesis: Annotation<z.infer<typeof SwotAndThesisSchema>>(),
  financials: Annotation<z.infer<typeof FinancialsSchema>>(),
  
  // Audit details
  mathErrors: Annotation<string[]>({
    reducer: (a, b) => a.concat(b),
    default: () => []
  }),
  retryCount: Annotation<number>({
    reducer: (a, b) => a + b,
    default: () => 0
  }),
  mathematicallyValid: Annotation<boolean>({
    reducer: (a, b) => b,
    default: () => true
  })
});

// --- Helper: Model instantiation inside nodes ---

function getNodeModel(options: AIServiceOptions): BaseChatModel {
  const provider = options.provider;
  const apiKey = options.apiKey || (provider === 'groq' ? process.env.GROQ_API_KEY : process.env.OPENAI_API_KEY);

  if (!apiKey) {
    throw new Error(`API key for provider "${provider}" is not configured.`);
  }

  switch (provider) {
    case 'groq':
      return new ChatGroq({
        apiKey,
        model: options.modelName || 'llama-3.3-70b-versatile',
        temperature: 0.1,
        maxRetries: 5,
      });
    case 'openai':
      return new ChatOpenAI({
        apiKey,
        model: options.modelName || 'gpt-4o-mini',
        temperature: 0.1,
        maxRetries: 5,
      });
    default:
      throw new Error(`Unsupported AI model provider: ${provider}`);
  }
}

// --- Node 0: Map-Reduce Chunker Node ---

async function preprocessChunksNode(state: typeof ResearchState.State) {
  // If text is short, skip chunking map-reduce and use it raw
  if (state.rawText.length < 25000) {
    return { condensedContext: state.rawText };
  }

  const chunks = splitTextIntoChunks(state.rawText, 12000, 1200);
  const model = getNodeModel(state.modelOptions);
  const structuredModel = model.withStructuredOutput(LocalExtractionSchema);
  
  const results: string[] = [];
  const isGroq = state.modelOptions.provider === 'groq';
  const delayMs = isGroq ? 1500 : 200;
  
  for (let i = 0; i < chunks.length; i++) {
    const chunk = chunks[i];
    
    // Add rate-limiting cooldown delay between sequential requests
    if (i > 0) {
      await new Promise(resolve => setTimeout(resolve, delayMs));
    }
    
    try {
      const systemPrompt = `You are a corporate data extraction analyst. Read the segment of an annual report / prospectus. Extract any relevant SWOT details, financials, or critical operations facts. Keep arrays empty if nothing is found.`;
      const userPrompt = `Company: ${state.companyName}\n\nSegment (Part ${i + 1} of ${chunks.length}):\n${chunk}`;
      
      const res = await structuredModel.invoke([
        ['system', systemPrompt],
        ['user', userPrompt]
      ]);
      
      const lines: string[] = [];
      if (res.relevantSWOT.length > 0) lines.push(`SWOT/Risk mentions: ${res.relevantSWOT.join(', ')}`);
      if (res.relevantFinancials.length > 0) lines.push(`Financial metrics: ${res.relevantFinancials.join(', ')}`);
      if (res.briefSectionSummary) lines.push(`Summary: ${res.briefSectionSummary}`);
      
      const chunkResult = lines.join('\n');
      if (chunkResult.trim()) {
        results.push(chunkResult);
      }
    } catch (err) {
      console.warn(`[Map-Reduce Chunker] Skip parsing chunk ${i + 1}:`, err);
    }
  }
  
  const mergedContext = results.join('\n\n---\n\n');
  return { condensedContext: mergedContext };
}

// --- Node 1: Company General details ---

async function extractCompanyGeneralNode(state: typeof ResearchState.State) {
  const model = getNodeModel(state.modelOptions);
  const structuredModel = model.withStructuredOutput(CompanyGeneralSchema);
  
  const systemPrompt = `You are an expert equity analyst. Read the provided text and extract general company corporate details: full name, stock ticker symbol, business operational overview, industry segment vertical overview, and a comprehensive narrative summary.`;
  const userPrompt = `Company: ${state.companyName}\n\nDocument Text:\n${state.condensedContext || state.rawText}`;
  
  const res = await structuredModel.invoke([
    ['system', systemPrompt],
    ['user', userPrompt]
  ]);
  
  return { companyGeneral: res };
}

// --- Node 2: SWOT & Investment Thesis ---

async function extractSwotNode(state: typeof ResearchState.State) {
  const model = getNodeModel(state.modelOptions);
  const structuredModel = model.withStructuredOutput(SwotAndThesisSchema);
  
  const systemPrompt = `You are an expert equity research auditor. Read the text and extract strategic qualitative metrics: SWOT strengths (highlights), SWOT weaknesses (risks), investment thesis case, and future growth triggers/pipelines.`;
  const userPrompt = `Company: ${state.companyName}\n\nDocument Text:\n${state.condensedContext || state.rawText}`;
  
  const res = await structuredModel.invoke([
    ['system', systemPrompt],
    ['user', userPrompt]
  ]);
  
  return { swotAndThesis: res };
}

// --- Node 3: Financials ---

async function extractFinancialsNode(state: typeof ResearchState.State) {
  const model = getNodeModel(state.modelOptions);
  const structuredModel = model.withStructuredOutput(FinancialsSchema);
  
  let feedback = '';
  if (state.mathErrors && state.mathErrors.length > 0) {
    feedback = `\n\n[WARNING: Previous extraction had errors! Please pay special attention to the following calculation issues and correct them:\n- ${state.mathErrors.join('\n- ')}]`;
  }
  
  const systemPrompt = `You are a chartered financial analyst. Carefully read the text and tables to extract revenue, EBITDA, and PAT/Net Profit series across fiscal periods. Also extract currentPrice, targetPrice, and recommendation.${feedback}`;
  const userPrompt = `Company: ${state.companyName}\n\nDocument Text:\n${state.condensedContext || state.rawText}`;
  
  const res = await structuredModel.invoke([
    ['system', systemPrompt],
    ['user', userPrompt]
  ]);
  
  return { financials: res };
}

// --- Node 4: Math Audit Router ---

function auditFinancialsNode(state: typeof ResearchState.State) {
  const errors: string[] = [];
  const financials = state.financials;

  if (financials) {
    const revMap = new Map(financials.revenue.map(r => [r.period, r.value]));
    financials.ebitda.forEach(e => {
      const revVal = revMap.get(e.period);
      if (revVal !== undefined && e.value > revVal) {
        errors.push(`EBITDA (${e.value}) is greater than Revenue (${revVal}) in period ${e.period}.`);
      }
    });

    const ebitdaMap = new Map(financials.ebitda.map(e => [e.period, e.value]));
    financials.pat.forEach(p => {
      const ebitdaVal = ebitdaMap.get(p.period);
      if (ebitdaVal !== undefined && p.value > ebitdaVal) {
        errors.push(`PAT (${p.value}) is greater than EBITDA (${ebitdaVal}) in period ${p.period}.`);
      }
    });
  }

  const hasErrors = errors.length > 0;
  const shouldRetry = hasErrors && state.retryCount < 2;

  if (shouldRetry) {
    return {
      mathErrors: errors,
      retryCount: 1,
      mathematicallyValid: false
    };
  }

  return {
    mathErrors: errors,
    mathematicallyValid: !hasErrors
  };
}

// --- Conditional router path decision ---

function routeAfterAudit(state: typeof ResearchState.State) {
  if (!state.mathematicallyValid && state.retryCount < 2) {
    console.warn(`[LangGraph Math Auditor] Audit failed with ${state.mathErrors.length} errors. Re-routing back to extractFinancials node (Retry count: ${state.retryCount}).`);
    return 'extract_financials';
  }
  return 'end';
}

// --- Build and Compile the Graph ---

const workflow = new StateGraph(ResearchState)
  .addNode('preprocess_chunks', preprocessChunksNode)
  .addNode('extract_general', extractCompanyGeneralNode)
  .addNode('extract_swot', extractSwotNode)
  .addNode('extract_financials', extractFinancialsNode)
  .addNode('audit_financials', auditFinancialsNode)
  
  // Starting flow runs chunking preprocessor first
  .addEdge(START, 'preprocess_chunks')
  
  // Once chunks are mapped and reduced, trigger parallel extractions
  .addEdge('preprocess_chunks', 'extract_general')
  .addEdge('preprocess_chunks', 'extract_swot')
  .addEdge('preprocess_chunks', 'extract_financials')
  
  // SWOT and general detail flows proceed straight to compilation END
  .addEdge('extract_general', END)
  .addEdge('extract_swot', END)
  
  // Financial workflow routes to audit check
  .addEdge('extract_financials', 'audit_financials')
  
  // Conditional audit routing path
  .addConditionalEdges('audit_financials', routeAfterAudit, {
    extract_financials: 'extract_financials',
    end: END
  });

export const langGraphResearchPipeline = workflow.compile();

/**
 * Executes the research pipeline and formats outputs to AIExtractionResult.
 */
export async function runResearchPipeline(
  companyName: string,
  rawText: string,
  options: AIServiceOptions
): Promise<AIExtractionResult> {
  const result = await langGraphResearchPipeline.invoke({
    companyName,
    rawText,
    modelOptions: options
  });

  return {
    companyName: result.companyGeneral.companyName,
    recommendation: result.financials.recommendation,
    highlights: result.swotAndThesis.highlights,
    investmentThesis: result.swotAndThesis.investmentThesis,
    outlook: result.companyGeneral.narrativeSummary,
    risks: result.swotAndThesis.risks,
    revenue: result.financials.revenue,
    ebitda: result.financials.ebitda,
    pat: result.financials.pat,
    ratios: null,
    currentPrice: result.financials.currentPrice,
    targetPrice: result.financials.targetPrice,
    narrativeSummary: result.companyGeneral.narrativeSummary,
    industryOverview: result.companyGeneral.industryOverview,
    businessOverview: result.companyGeneral.businessOverview,
    futureGrowth: result.swotAndThesis.futureGrowth
  };
}
