import { Annotation, StateGraph, START, END } from '@langchain/langgraph';
import { ChatGroq } from '@langchain/groq';
import { z } from 'zod';
import { prisma } from '@/lib/db';
import { AIServiceOptions } from './langchain-service';
import { AIExtractionResult } from './schema';
import { getModelForRequest, recordActualUsage } from './model-router';
import { withRateLimitRetry, RateLimitError } from './retry-wrapper';

// --- Helper: Simple Character Chunker with overlap ---

function splitTextIntoChunks(text: string, chunkSize = 20000, overlap = 2000): string[] {
  const chunks: string[] = [];
  let start = 0;
  while (start < text.length) {
    const end = Math.min(start + chunkSize, text.length);
    chunks.push(text.substring(start, end));
    start += chunkSize - overlap;
    if (end === text.length) break;
  }
  return chunks;
}

// --- Specialized Node Zod Sub-schemas ---

export const LocalExtractionSchema = z.object({
  relevantSWOT: z.array(z.string()).describe('SWOT factors or risk signals found in this section (empty if none)'),
  relevantFinancials: z.array(z.string()).describe('Key financial figures, EBITDA, revenues, or targets mentioned in this section (empty if none)'),
  briefSectionSummary: z.string().describe('1-2 sentence high-density summary of operational facts in this section')
});

export const CompanyGeneralSchema = z.object({
  companyName: z.string().describe('Full corporate name of the target entity'),
  ticker: z.string().describe('Stock market ticker symbol'),
  narrativeSummary: z.string().describe('Narrative summary of findings (outlook, recommendation, key drivers)'),
  industryOverview: z.string().describe('High-level outlook of the industry vertical'),
  businessOverview: z.string().describe('Brief operational overview of business divisions')
});

export const SwotAndThesisSchema = z.object({
  highlights: z.array(z.string()).describe('Key highlights (strengths, expansion, strategic positioning)'),
  investmentThesis: z.string().describe('Main investment case and rationale'),
  risks: z.array(z.string()).describe('Primary business and financial risks/weaknesses'),
  futureGrowth: z.string().describe('Key growth drivers and pipeline plans')
});

export const FinancialsSchema = z.object({
  revenue: z.array(z.object({
    period: z.string().describe('Fiscal period, e.g. FY23, FY24, FY25'),
    value: z.number().describe('Revenue figure value'),
    unit: z.string().describe('Cr or Mn')
  })).describe('Revenue statement entries'),
  ebitda: z.array(z.object({
    period: z.string().describe('Fiscal period'),
    value: z.number().describe('EBITDA value'),
    unit: z.string().describe('Cr or Mn')
  })).describe('EBITDA statement entries'),
  pat: z.array(z.object({
    period: z.string().describe('Fiscal period'),
    value: z.number().describe('PAT value'),
    unit: z.string().describe('Cr or Mn')
  })).describe('PAT/Net Profit statement entries'),
  currentPrice: z.number().describe('Current market stock trading price'),
  targetPrice: z.number().describe('Stock price target recommendation'),
  recommendation: z.enum(['BUY', 'HOLD', 'ACCUMULATE', 'REDUCE', 'SELL']).describe('Investment rating')
});

// --- State Definition ---

export const ResearchState = Annotation.Root({
  rawText: Annotation<string>(),
  companyName: Annotation<string>(),
  modelOptions: Annotation<AIServiceOptions>(),
  
  // Condensed summary generated by map-reduce preprocessor
  condensedContext: Annotation<string>({
    reducer: (a, b) => b,
    default: () => ''
  }),

  // Extract results
  companyGeneral: Annotation<z.infer<typeof CompanyGeneralSchema>>(),
  swotAndThesis: Annotation<z.infer<typeof SwotAndThesisSchema>>(),
  financials: Annotation<z.infer<typeof FinancialsSchema>>(),
  
  // Audit details
  mathErrors: Annotation<string[]>({
    reducer: (a, b) => a.concat(b),
    default: () => []
  }),
  retryCount: Annotation<number>({
    reducer: (a, b) => a + b,
    default: () => 0
  }),
  mathematicallyValid: Annotation<boolean>({
    reducer: (a, b) => b,
    default: () => true
  }),
  /** Tracks which model actually ran financials extraction (for reviewer audit trail) */
  modelUsedForFinancials: Annotation<string>({
    reducer: (a, b) => b || a,
    default: () => ''
  })
});

// --- Helper: Preprocessor model (always high-TPM 8B) ---

function getPreprocessorModel(options: AIServiceOptions): ChatGroq {
  const apiKey = options.apiKey || process.env.GROQ_API_KEY || '';
  if (!apiKey) throw new Error('Groq API key not configured for preprocessor model.');
  return new ChatGroq({
    apiKey,
    model: 'llama-3.1-8b-instant', // 500,000 TPM — safe for bulk chunking
    temperature: 0.1,
    maxRetries: 5,
  });
}

// --- Node 0: Map-Reduce Chunker Node ---

async function preprocessChunksNode(state: typeof ResearchState.State) {
  // If text is short, skip chunking map-reduce and use it raw
  if (state.rawText.length < 25000) {
    return { condensedContext: state.rawText };
  }

  const chunks = splitTextIntoChunks(state.rawText, 12000, 1200);
  const model = getPreprocessorModel(state.modelOptions);
  const structuredModel = model.withStructuredOutput(LocalExtractionSchema);
  
  const results: string[] = [];
  const delayMs = 150; // fast delay for high-rate-limit base preprocessor model
  
  for (let i = 0; i < chunks.length; i++) {
    const chunk = chunks[i];
    
    // Add rate-limiting cooldown delay between sequential requests
    if (i > 0) {
      await new Promise(resolve => setTimeout(resolve, delayMs));
    }
    
    try {
      const systemPrompt = `You are a corporate data extraction analyst. Read the segment of an annual report / prospectus. Extract any relevant SWOT details, financials, or critical operations facts. Keep arrays empty if nothing is found.`;
      const userPrompt = `Company: ${state.companyName}\n\nSegment (Part ${i + 1} of ${chunks.length}):\n${chunk}`;
      
      const res = await structuredModel.invoke([
        ['system', systemPrompt],
        ['user', userPrompt]
      ]);
      
      const lines: string[] = [];
      if (res.relevantSWOT.length > 0) lines.push(`SWOT/Risk mentions: ${res.relevantSWOT.join(', ')}`);
      if (res.relevantFinancials.length > 0) lines.push(`Financial metrics: ${res.relevantFinancials.join(', ')}`);
      if (res.briefSectionSummary) lines.push(`Summary: ${res.briefSectionSummary}`);
      
      const chunkResult = lines.join('\n');
      if (chunkResult.trim()) {
        results.push(chunkResult);
      }
    } catch (err) {
      console.warn(`[Map-Reduce Chunker] Skip parsing chunk ${i + 1}:`, err);
    }
  }
  
  const mergedContext = results.join('\n\n---\n\n');
  return { condensedContext: mergedContext };
}

// --- Node 1: Company General details ---

async function extractCompanyGeneralNode(state: typeof ResearchState.State) {
  const contextText = state.condensedContext || state.rawText;
  const systemPrompt = `You are an expert equity analyst. Read the provided text and extract general company corporate details: full name, stock ticker symbol, business operational overview, industry segment vertical overview, and a comprehensive narrative summary.`;
  const userPrompt = `Company: ${state.companyName}\n\nDocument Text:\n${contextText}`;
  const fullPrompt = systemPrompt + userPrompt;

  // Pre-flight: checks request size vs TPM ceiling, waits for real budget, reroutes if needed
  const { model, modelName, downgraded } = await getModelForRequest(
    state.modelOptions, fullPrompt, 'llama-3.3-70b-versatile'
  );
  if (downgraded) {
    console.warn(`[extract_general] Rerouted to ${modelName} due to request size — review output quality for dense documents.`);
  }

  const structuredModel = model.withStructuredOutput(CompanyGeneralSchema);
  const res = await withRateLimitRetry(() =>
    structuredModel.invoke([['system', systemPrompt], ['user', userPrompt]])
  );

  recordActualUsage(modelName, fullPrompt, JSON.stringify(res));
  return { companyGeneral: res };
}

// --- Node 2: SWOT & Investment Thesis ---

async function extractSwotNode(state: typeof ResearchState.State) {
  const contextText = state.condensedContext || state.rawText;
  const systemPrompt = `You are an expert equity research auditor. Read the text and extract strategic qualitative metrics: SWOT strengths (highlights), SWOT weaknesses (risks), investment thesis case, and future growth triggers/pipelines.`;
  const userPrompt = `Company: ${state.companyName}\n\nDocument Text:\n${contextText}`;
  const fullPrompt = systemPrompt + userPrompt;

  const { model, modelName, downgraded } = await getModelForRequest(
    state.modelOptions, fullPrompt, 'llama-3.3-70b-versatile'
  );
  if (downgraded) {
    console.warn(`[extract_swot] Rerouted to ${modelName} due to request size.`);
  }

  const structuredModel = model.withStructuredOutput(SwotAndThesisSchema);
  const res = await withRateLimitRetry(() =>
    structuredModel.invoke([['system', systemPrompt], ['user', userPrompt]])
  );

  recordActualUsage(modelName, fullPrompt, JSON.stringify(res));
  return { swotAndThesis: res };
}

// --- Node 3: Financials ---

async function extractFinancialsNode(state: typeof ResearchState.State) {
  const contextText = state.condensedContext || state.rawText;
  let feedback = '';
  if (state.mathErrors && state.mathErrors.length > 0) {
    feedback = `\n\n[WARNING: Previous extraction had errors! Please pay special attention to the following calculation issues and correct them:\n- ${state.mathErrors.join('\n- ')}]`;
  }

  const systemPrompt = `You are a chartered financial analyst. Carefully read the text and tables to extract revenue, EBITDA, and PAT/Net Profit series across fiscal periods. Also extract currentPrice, targetPrice, and recommendation.${feedback}`;
  const userPrompt = `Company: ${state.companyName}\n\nDocument Text:\n${contextText}`;
  const fullPrompt = systemPrompt + userPrompt;

  const { model, modelName, downgraded } = await getModelForRequest(
    state.modelOptions, fullPrompt, 'llama-3.3-70b-versatile'
  );
  if (downgraded) {
    console.warn(`[extract_financials] Rerouted to ${modelName} due to request size — quality may differ on dense documents.`);
  }

  const structuredModel = model.withStructuredOutput(FinancialsSchema);
  const res = await withRateLimitRetry(() =>
    structuredModel.invoke([['system', systemPrompt], ['user', userPrompt]])
  );

  recordActualUsage(modelName, fullPrompt, JSON.stringify(res));
  return { financials: res, modelUsedForFinancials: modelName };
}

// --- Node 4: Math Audit Router ---

function auditFinancialsNode(state: typeof ResearchState.State) {
  const errors: string[] = [];
  const financials = state.financials;

  if (financials) {
    const revMap = new Map(financials.revenue.map(r => [r.period, r.value]));
    financials.ebitda.forEach(e => {
      const revVal = revMap.get(e.period);
      if (revVal !== undefined && e.value > revVal) {
        errors.push(`EBITDA (${e.value}) is greater than Revenue (${revVal}) in period ${e.period}.`);
      }
    });

    const ebitdaMap = new Map(financials.ebitda.map(e => [e.period, e.value]));
    financials.pat.forEach(p => {
      const ebitdaVal = ebitdaMap.get(p.period);
      if (ebitdaVal !== undefined && p.value > ebitdaVal) {
        errors.push(`PAT (${p.value}) is greater than EBITDA (${ebitdaVal}) in period ${p.period}.`);
      }
    });
  }

  const hasErrors = errors.length > 0;
  const shouldRetry = hasErrors && state.retryCount < 2;

  if (shouldRetry) {
    return {
      mathErrors: errors,
      retryCount: 1,
      mathematicallyValid: false
    };
  }

  return {
    mathErrors: errors,
    mathematicallyValid: !hasErrors
  };
}

// --- Conditional router path decision ---

function routeAfterAudit(state: typeof ResearchState.State) {
  if (!state.mathematicallyValid && state.retryCount < 2) {
    console.warn(`[LangGraph Math Auditor] Audit failed with ${state.mathErrors.length} errors. Re-routing back to extractFinancials node (Retry count: ${state.retryCount}).`);
    return 'extract_financials';
  }
  return 'end';
}

// --- Build and Compile the Graph ---

const workflow = new StateGraph(ResearchState)
  .addNode('preprocess_chunks', preprocessChunksNode)
  .addNode('extract_general', extractCompanyGeneralNode)
  .addNode('extract_swot', extractSwotNode)
  .addNode('extract_financials', extractFinancialsNode)
  .addNode('audit_financials', auditFinancialsNode)
  
  // Starting flow runs chunking preprocessor first
  .addEdge(START, 'preprocess_chunks')
  
  // Run extractions sequentially with built-in model rate limit cooling delays
  .addEdge('preprocess_chunks', 'extract_general')
  .addEdge('extract_general', 'extract_swot')
  .addEdge('extract_swot', 'extract_financials')
  
  // Financial workflow routes to audit check
  .addEdge('extract_financials', 'audit_financials')
  
  // Conditional audit routing path
  .addConditionalEdges('audit_financials', routeAfterAudit, {
    extract_financials: 'extract_financials',
    end: END
  });

export const langGraphResearchPipeline = workflow.compile();

/**
 * Executes the research pipeline and formats outputs to AIExtractionResult.
 */
export async function runResearchPipeline(
  companyName: string,
  rawText: string,
  options: AIServiceOptions
): Promise<AIExtractionResult> {
  const result = await langGraphResearchPipeline.invoke({
    companyName,
    rawText,
    modelOptions: options
  });

  return {
    companyName: result.companyGeneral.companyName,
    recommendation: result.financials.recommendation,
    highlights: result.swotAndThesis.highlights,
    investmentThesis: result.swotAndThesis.investmentThesis,
    outlook: result.companyGeneral.narrativeSummary,
    risks: result.swotAndThesis.risks,
    revenue: result.financials.revenue,
    ebitda: result.financials.ebitda,
    pat: result.financials.pat,
    ratios: null,
    currentPrice: result.financials.currentPrice,
    targetPrice: result.financials.targetPrice,
    narrativeSummary: result.companyGeneral.narrativeSummary,
    industryOverview: result.companyGeneral.industryOverview,
    businessOverview: result.companyGeneral.businessOverview,
    futureGrowth: result.swotAndThesis.futureGrowth
  };
}

/**
 * Stateful pipeline runner that saves intermediate progress to the database.
 * If execution fails, it can be resumed starting from the failed step.
 */
export async function runOrResumeResearchPipeline(
  jobId: string,
  companyName?: string,
  rawText?: string,
  options?: AIServiceOptions,
  resume = false
): Promise<AIExtractionResult> {
  let job;

  if (resume) {
    job = await prisma.extractionJob.findUnique({
      where: { id: jobId }
    });
    if (!job) {
      throw new Error(`Extraction job with ID ${jobId} not found.`);
    }
  } else {
    if (!companyName || !rawText || !options) {
      throw new Error('Missing parameters to initialize a new extraction job.');
    }
    // Upsert job in DB (idempotent — the API route may have already created it)
    job = await prisma.extractionJob.upsert({
      where: { id: jobId },
      update: {
        companyName,
        rawText,
        status: 'running',
        stepIndex: 0,
        errorMessage: null,
        retryAfterSeconds: null
      },
      create: {
        id: jobId,
        companyName: companyName!,
        fileName: 'uploaded_document.pdf', // fallback — API route upsert always runs first with real name
        rawText: rawText!,
        status: 'running',
        stepIndex: 0
      }
    });
  }

  // Initialize graph state variables
  const state = {
    companyName: job.companyName,
    rawText: job.rawText,
    condensedContext: job.condensedContext || '',
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    companyGeneral: job.companyGeneral ? (job.companyGeneral as any) : null,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    swotAndThesis: job.swotAndThesis ? (job.swotAndThesis as any) : null,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    financials: job.financials ? (job.financials as any) : null,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    mathErrors: job.mathErrors ? (job.mathErrors as any[]) : [],
    retryCount: 0,
    mathematicallyValid: true,
    modelUsedForFinancials: '',
    modelOptions: options || {
      provider: 'groq',
      apiKey: ''
    }
  };

  try {
    // Step 0: Preprocessing (Chunking / Map-Reduce)
    if (job.stepIndex <= 0) {
      await prisma.extractionJob.update({
        where: { id: jobId },
        data: { status: 'running', stepIndex: 0 }
      });
      const preprocessOut = await preprocessChunksNode(state);
      state.condensedContext = preprocessOut.condensedContext || state.rawText;
      
      await prisma.extractionJob.update({
        where: { id: jobId },
        data: {
          condensedContext: state.condensedContext,
          stepIndex: 1
        }
      });
    }

    // Step 1: General Details
    if (job.stepIndex <= 1) {
      await prisma.extractionJob.update({
        where: { id: jobId },
        data: { status: 'running', stepIndex: 1 }
      });
      const generalOut = await extractCompanyGeneralNode(state);
      state.companyGeneral = generalOut.companyGeneral;

      await prisma.extractionJob.update({
        where: { id: jobId },
        data: {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          companyGeneral: state.companyGeneral as any,
          stepIndex: 2
        }
      });
    }

    // Step 2: SWOT & Thesis
    if (job.stepIndex <= 2) {
      await prisma.extractionJob.update({
        where: { id: jobId },
        data: { status: 'running', stepIndex: 2 }
      });
      const swotOut = await extractSwotNode(state);
      state.swotAndThesis = swotOut.swotAndThesis;

      await prisma.extractionJob.update({
        where: { id: jobId },
        data: {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          swotAndThesis: state.swotAndThesis as any,
          stepIndex: 3
        }
      });
    }

    // Step 3: Financials & Audit
    if (job.stepIndex <= 3) {
      await prisma.extractionJob.update({
        where: { id: jobId },
        data: { status: 'running', stepIndex: 3 }
      });
      
      let financialsOut = await extractFinancialsNode(state);
      state.financials = financialsOut.financials;

      // Audit financials
      let auditOut = auditFinancialsNode(state);
      state.mathErrors = auditOut.mathErrors || [];
      state.mathematicallyValid = auditOut.mathematicallyValid || false;

      // Handle audit retry loop if needed (up to 1 retry)
      if (!state.mathematicallyValid) {
        console.warn('[Sequential Runner] Audit failed. Retrying financials extraction...');
        state.retryCount = 1;
        financialsOut = await extractFinancialsNode(state);
        state.financials = financialsOut.financials;
        
        auditOut = auditFinancialsNode(state);
        state.mathErrors = auditOut.mathErrors || [];
        state.mathematicallyValid = auditOut.mathematicallyValid || false;
      }

      await prisma.extractionJob.update({
        where: { id: jobId },
        data: {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          financials: state.financials as any,
          mathErrors: state.mathErrors,
          stepIndex: 4,
          status: 'completed'
        }
      });
    }

    // Return compiled result
    return {
      companyName: state.companyGeneral.companyName,
      recommendation: state.financials.recommendation,
      highlights: state.swotAndThesis.highlights,
      investmentThesis: state.swotAndThesis.investmentThesis,
      outlook: state.companyGeneral.narrativeSummary,
      risks: state.swotAndThesis.risks,
      revenue: state.financials.revenue,
      ebitda: state.financials.ebitda,
      pat: state.financials.pat,
      ratios: null,
      currentPrice: state.financials.currentPrice,
      targetPrice: state.financials.targetPrice,
      narrativeSummary: state.companyGeneral.narrativeSummary,
      industryOverview: state.companyGeneral.industryOverview,
      businessOverview: state.companyGeneral.businessOverview,
      futureGrowth: state.swotAndThesis.futureGrowth,
      // Audit trail: which model ran the financials extraction
      modelUsedForFinancials: state.modelUsedForFinancials || null
    };

  } catch (err: unknown) {
    if (err instanceof RateLimitError) {
      // Temporary rate-limit — job is resumable, NOT permanently failed
      console.warn(`[Pipeline] Throttled. Auto-resume in ${err.retryAfterSeconds}s.`);
      await prisma.extractionJob.update({
        where: { id: jobId },
        data: {
          status: 'throttled',
          retryAfterSeconds: err.retryAfterSeconds,
          errorMessage: `Rate limited — auto-resume in ${err.retryAfterSeconds}s`,
        },
      });
      throw err; // re-throw typed signal so API route can tell client to auto-poll
    }

    const errorMsg = err instanceof Error ? err.message : 'Unknown pipeline error';
    await prisma.extractionJob.update({
      where: { id: jobId },
      data: { status: 'failed', errorMessage: errorMsg }
    });
    throw err;
  }
}
