/**
 * Synthesis & Report Generation Subagent (Phase 14)
 * Assembles multi-source intelligence from Document Agent, Modeling Agent,
 * and Market Intel Agent into publication-grade report sections.
 *
 * FIX: All section content is now generated by an LLM using REAL input data
 * (modeling output, market intel, concall transcripts). The old hardcoded
 * "14.2% CAGR" / "Segment A: 58%" template strings have been removed entirely.
 * Each section falls back to a clearly-labelled "data pending" placeholder
 * when real inputs are absent — never fake numbers.
 */

import {
  ModelingOutput,
  ReportSection,
  ReportSectionName,
} from "@/types/plan4";
import { ConsistencyCheckerTool, ConsistencyCheckResult } from "../tools/consistency-checker-tool";
import { SectionStore } from "@/lib/report/section-store";
import { trajectoryBus } from "../trajectory-emitter";
import { prisma } from "@/lib/db";
import { getModelForRequest } from "@/lib/ai/model-router";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import type { ConcallTranscriptResult } from "../tools/concall-transcript-tool";

export interface SynthesisInput {
  planId: string;
  runId?: string;
  ticker: string;
  companyName: string;
  depth?: string;
  documentData?: {
    filings?: unknown[];
    concallQuotes?: { speaker?: string; quote: string; topic?: string }[];
  };
  modelingData?: ModelingOutput;
  marketIntelData?: {
    peRatio?: number;
    marketCapCr?: number;
    promoterShareholding?: number;
    creditRating?: string;
    newsItems?: { title: string; sentiment: string }[];
    benchmarkTableMarkdown?: string;
  };
  /** Concall transcripts from DocumentAgent — used for management Q&A section */
  concallTranscripts?: ConcallTranscriptResult[];
}

export interface SynthesisOutput {
  runId: string;
  planId: string;
  ticker: string;
  companyName: string;
  sections: ReportSection[];
  consistencyCheck: ConsistencyCheckResult;
  completedAt: string;
}

// ─── System prompt for section generation ─────────────────────────────────────

const SYNTHESIS_SYSTEM_PROMPT = `You are an institutional equity research analyst for the Indian capital markets.
Write each report section in professional, concise financial research prose.
Rules:
- Use ONLY the data provided in the user message. Never invent numbers.
- If a specific figure is not in the provided data, say "data pending [field]" — do not fabricate.
- Write for a professional investor audience (buy-side / sell-side).
- Use INR (₹) currency notation. Use Indian numbering (Cr for crores, L for lakhs).
- Keep sections factual, specific, and citation-ready.
- Output only the section content — no headings, no meta-commentary.`;

// ─── LLM Section Generator ─────────────────────────────────────────────────────

async function generateSectionWithLLM(
  sectionName: string,
  prompt: string,
  apiKey?: string
): Promise<string | null> {
  try {
    const { model } = await getModelForRequest(
      { provider: "groq", apiKey },
      prompt,
    );
    const response = await model.invoke([
      new SystemMessage(SYNTHESIS_SYSTEM_PROMPT),
      new HumanMessage(prompt),
    ]);
    const content = typeof response.content === "string" ? response.content : JSON.stringify(response.content);
    return content.trim() || null;
  } catch (err) {
    console.warn(`[SynthesisAgent] LLM generation failed for section "${sectionName}":`, err);
    return null;
  }
}

// ─── Section prompt builders — inject real data, never defaults ───────────────

function buildExecutiveSummaryPrompt(input: SynthesisInput): string {
  const m = input.modelingData;
  const mi = input.marketIntelData;
  const valuation = m
    ? `Base-case target price: ₹${Math.round(m.baseTargetPrice)}/share (Bull: ₹${Math.round(m.bullCasePrice)}, Bear: ₹${Math.round(m.bearCasePrice)}).
       Model assumptions: ${JSON.stringify(m.assumptions)}.`
    : "Financial model output: not yet available.";

  const creditRating = mi?.creditRating ?? "not available";
  const peerBenchmark = mi?.benchmarkTableMarkdown
    ? `Peer benchmark summary:\n${mi.benchmarkTableMarkdown.slice(0, 600)}`
    : "Peer benchmark: not yet available.";

  return `Write an Executive Summary for ${input.companyName} (NSE: ${input.ticker}) for an institutional equity research initiation report.

Available data:
- ${valuation}
- Credit profile: ${creditRating}
- ${peerBenchmark}

The executive summary must:
1. State the investment rating and target price (if modeled).
2. Summarize the 3 most important investment thesis points supported by the data above.
3. Mention the DCF methodology and key assumptions if valuation data is available.
4. Be 150–200 words.`;
}

function buildBusinessDescriptionPrompt(input: SynthesisInput): string {
  const filingCount = (input.documentData?.filings ?? []).length;
  return `Write the Business Description section for ${input.companyName} (NSE: ${input.ticker}).

Available data:
- Exchange filings fetched: ${filingCount} documents
- Company: ${input.companyName}
- Ticker: ${input.ticker}

Important: Do NOT invent segment revenue splits or specific business unit data. 
Describe what is known about the company's industry position, key business lines, and competitive context 
in general terms. If specific segment data is not provided, clearly state "segment data pending from filings."
Keep this to 120–150 words.`;
}

function buildFinancialAnalysisPrompt(input: SynthesisInput): string {
  const m = input.modelingData;
  if (!m) {
    return `Write a Financial Analysis placeholder for ${input.companyName} (${input.ticker}).
Note that the financial model has not yet been computed. State clearly that "financial model output is pending" 
and describe what will be covered in this section once the model runs (Revenue, EBITDA, PAT, ROCE).
Keep this to 80–100 words.`;
  }

  return `Write the Financial Analysis section for ${input.companyName} (NSE: ${input.ticker}).

DCF Model Output:
- Base-case target price: ₹${Math.round(m.baseTargetPrice)}/share
- Model assumptions: ${JSON.stringify(m.assumptions)}
- Projection type: ${m.modelType}

Market intelligence:
- P/E Ratio: ${input.marketIntelData?.peRatio ?? "data pending"}
- Market Cap: ${input.marketIntelData?.marketCapCr ? `₹${input.marketIntelData.marketCapCr.toLocaleString()} Cr` : "data pending"}
- Promoter holding: ${input.marketIntelData?.promoterShareholding ? `${input.marketIntelData.promoterShareholding}%` : "data pending"}

Summarize the financial health and profitability trajectory based only on the above data.
Do not fabricate CAGR percentages or margin figures not present in the model output.
Be 150–180 words.`;
}

function buildValuationSectionPrompt(input: SynthesisInput): string {
  const m = input.modelingData;
  if (!m) {
    return `Write a Valuation section placeholder for ${input.companyName} (${input.ticker}).
State clearly that "valuation model output is pending completion of the financial model phase."
Keep this to 60 words.`;
  }

  const benchmarkTable = input.marketIntelData?.benchmarkTableMarkdown
    ? `\nPeer benchmark table:\n${input.marketIntelData.benchmarkTableMarkdown}`
    : "";

  return `Write the Valuation section for ${input.companyName} (NSE: ${input.ticker}).

Model results:
- Model type: ${m.modelType.toUpperCase()}
- Base case: ₹${Math.round(m.baseTargetPrice)}/share
- Bull case: ₹${Math.round(m.bullCasePrice)}/share
- Bear case: ₹${Math.round(m.bearCasePrice)}/share
- Assumptions: ${JSON.stringify(m.assumptions)}
${benchmarkTable}

Explain the valuation methodology and derive the target price from the model output above.
Present the bull/bear/base case scenarios. Reference peer multiples if the benchmark table is available.
Do not add assumptions not present in the data above.
Be 160–200 words.`;
}

function buildRisksSectionPrompt(input: SynthesisInput): string {
  const newsItems = input.marketIntelData?.newsItems ?? [];
  const newsContext = newsItems.length > 0
    ? `Recent news sentiment: ${newsItems.slice(0, 5).map(n => `"${n.title}" (${n.sentiment})`).join("; ")}`
    : "Recent news: not available.";

  return `Write the Key Risks section for ${input.companyName} (NSE: ${input.ticker}).

Context:
- Credit profile: ${input.marketIntelData?.creditRating ?? "data pending"}
- ${newsContext}

List 3–5 key investment risks specific to ${input.companyName}'s business and sector.
For each risk, provide a one-sentence mitigant.
Do not fabricate specific financial impact percentages — use qualitative risk language.
Be 150–180 words.`;
}

function buildConcallQASectionPrompt(input: SynthesisInput): string {
  // Prefer structured concall quotes from DocumentAgent
  const transcripts = input.concallTranscripts ?? [];
  const legacyQuotes = input.documentData?.concallQuotes ?? [];

  const allQuotes = transcripts.flatMap(t => t.quotes).slice(0, 8);

  if (allQuotes.length > 0) {
    const formatted = allQuotes
      .map(q => `[${q.quarter}] ${q.speakerRole}: "${q.quote}" — Topic: ${q.topic} (${q.sentiment})`)
      .join("\n");

    return `Synthesize the Management Q&A Highlights section for ${input.companyName} (${input.ticker}) using these earnings call quotes:

${formatted}

Summarize the key management messages, guidance, and tone. Group by topic (revenue guidance, margin, capex, risks).
Be 150–180 words. Do not add quotes or claims not in the above data.`;
  }

  if (legacyQuotes.length > 0) {
    const formatted = legacyQuotes
      .map(q => `${q.speaker ?? "Management"}: "${q.quote}"`)
      .join("\n");

    return `Synthesize the Management Q&A Highlights for ${input.companyName} from these quotes:\n\n${formatted}\n\nBe 120–150 words.`;
  }

  return `Write a Management Q&A Highlights placeholder for ${input.companyName} (${input.ticker}).
State clearly that "earnings call transcript data is pending — this section will be populated once concall transcripts are fetched from Screener.in."
Keep this to 50 words.`;
}

// ─── Synthesis Agent ──────────────────────────────────────────────────────────

export class SynthesisAgent {
  /**
   * Main entry point for Synthesis Subagent execution.
   * All section content is LLM-generated from real input data.
   */
  public async run(input: SynthesisInput, apiKey?: string): Promise<SynthesisOutput> {
    const runId = input.runId ?? `synth_${Date.now()}`;
    const startTime = Date.now();

    trajectoryBus.emitEvent(
      input.planId,
      "subagent_start",
      { agent: "synthesis", summary: `Synthesizing report sections for ${input.companyName} (${input.ticker}) using live research data...` }
    );

    // Generate all sections via LLM, sequentially to respect rate limits
    const sectionDefs: { name: ReportSectionName; promptFn: () => string; citationsHint: string[] }[] = [
      {
        name: "executive_summary",
        promptFn: () => buildExecutiveSummaryPrompt(input),
        citationsHint: ["bse_filings", "dcf_model", "screener_market_intel"],
      },
      {
        name: "business_description",
        promptFn: () => buildBusinessDescriptionPrompt(input),
        citationsHint: ["annual_report"],
      },
      {
        name: "financial_analysis",
        promptFn: () => buildFinancialAnalysisPrompt(input),
        citationsHint: ["screener_financials", "dcf_model"],
      },
      {
        name: "valuation",
        promptFn: () => buildValuationSectionPrompt(input),
        citationsHint: ["dcf_model", "screener_peer_multiples"],
      },
      {
        name: "key_risks",
        promptFn: () => buildRisksSectionPrompt(input),
        citationsHint: ["sector_news", "credit_rating"],
      },
      {
        name: "management_qa_highlights",
        promptFn: () => buildConcallQASectionPrompt(input),
        citationsHint: ["concall_transcript"],
      },
    ];

    const sections: ReportSection[] = [];

    for (const def of sectionDefs) {
      const prompt = def.promptFn();
      const content =
        (await generateSectionWithLLM(def.name, prompt, apiKey)) ??
        `[${def.name} — data pending: LLM generation unavailable. ` +
        `Please ensure an API key is configured and retry.]`;

      const section: ReportSection = {
        name: def.name,
        content,
        citations: def.citationsHint,
        lastUpdatedAt: new Date().toISOString(),
        agentConfidence: content.includes("data pending") ? 0.2 : 0.85,
      };

      sections.push(section);
      SectionStore.saveSectionVersion(input.planId, section.name, section.content, section.citations);
      trajectoryBus.emitEvent(input.planId, "draft_updated", {
        sectionName: def.name,
        preview: content.slice(0, 120) + "…",
      });
    }

    // Run consistency check on executive summary vs modeling output
    const consistencyCheck = ConsistencyCheckerTool.checkSectionConsistency(
      "executive_summary",
      sections.find(s => s.name === "executive_summary")?.content ?? "",
      input.modelingData,
      undefined,
    );

    trajectoryBus.emitEvent(
      input.planId,
      "milestone_done",
      {
        milestoneRef: "synthesise",
        summary: `Synthesized ${sections.length} sections for ${input.companyName}. Consistency Score: ${(consistencyCheck.score * 100).toFixed(0)}%`,
      },
      "synthesise"
    );

    // DB record update (graceful for offline/demo tests)
    const runExists = await prisma.subagentRun.findUnique({ where: { id: runId } }).catch(() => null);
    if (runExists) {
      await prisma.subagentRun.update({
        where: { id: runId },
        data: {
          status: "completed",
          outputJson: { sections, consistencyCheck } as unknown as import("@prisma/client").Prisma.JsonObject,
          latencyMs: Date.now() - startTime,
        },
      }).catch(() => {});
    }

    return {
      runId,
      planId: input.planId,
      ticker: input.ticker,
      companyName: input.companyName,
      sections,
      consistencyCheck,
      completedAt: new Date().toISOString(),
    };
  }
}

export const synthesisAgent = new SynthesisAgent();
