/**
 * Synthesis & Report Generation Subagent (Phase 14)
 * Assembles multi-source intelligence from Document Agent, Modeling Agent,
 * and Market Intel Agent into publication-grade report sections.
 *
 * FIX: All section content is now generated by an LLM using REAL input data
 * (modeling output, market intel, concall transcripts). The old hardcoded
 * "14.2% CAGR" / "Segment A: 58%" template strings have been removed entirely.
 * Each section falls back to a clearly-labelled "data pending" placeholder
 * when real inputs are absent — never fake numbers.
 */

import {
  ModelingOutput,
  ReportSection,
  ReportSectionName,
} from "@/types/plan4";
import { ConsistencyCheckerTool, ConsistencyCheckResult } from "../tools/consistency-checker-tool";
import { SectionStore } from "@/lib/report/section-store";
import { trajectoryBus } from "../trajectory-emitter";
import { prisma } from "@/lib/db";
import { getModelForRequest } from "@/lib/ai/model-router";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import type { ConcallTranscriptResult } from "../tools/concall-transcript-tool";

export interface SynthesisInput {
  planId: string;
  runId?: string;
  ticker: string;
  companyName: string;
  depth?: string;
  documentData?: {
    filings?: unknown[];
    /** Typed filing titles & URLs for business description context */
    filingTitles?: { type: string; title: string; url: string; date: string }[];
    concallQuotes?: { speaker?: string; quote: string; topic?: string }[];
    totalDocumentsFetched?: number;
    isLiveData?: boolean;
  };
  modelingData?: ModelingOutput & {
    assumptions?: {
      isDerivedFromExtractedData?: string;  // "True" | "False"
      financialSource?: string;
      disclaimer?: string;
      [key: string]: unknown;
    };
  };
  marketIntelData?: {
    peRatio?: number;
    marketCapCr?: number;
    promoterShareholding?: number;
    creditRating?: string;
    creditRatingIsLive?: boolean;    // false when no real rating found
    newsItems?: { title: string; sentiment: string; isLiveData?: boolean }[];
    newsIsLive?: boolean;            // false when no real news fetched
    benchmarkTableMarkdown?: string;
    screenerIsLive?: boolean;        // false when Screener scrape failed
  };
  /** Concall transcripts from DocumentAgent — used for management Q&A section */
  concallTranscripts?: ConcallTranscriptResult[];
}

export interface DataSourceSummary {
  bseNseFilings: { count: number; isLive: boolean };
  concallTranscript: { quotesFound: number; isLive: boolean };
  screenerMarketData: { isLive: boolean };
  creditRating: { isLive: boolean; found: boolean };
  news: { count: number; isLive: boolean };
  dcfModel: { isDerivedFromRealData: boolean; source: string };
}

export interface SynthesisOutput {
  runId: string;
  planId: string;
  ticker: string;
  companyName: string;
  sections: ReportSection[];
  consistencyCheck: ConsistencyCheckResult;
  dataSources: DataSourceSummary;
  completedAt: string;
}

// ─── System prompt for section generation ─────────────────────────────────────

const SYNTHESIS_SYSTEM_PROMPT = `You are an institutional equity research analyst for the Indian capital markets.
Write each report section in professional, concise financial research prose.
Rules:
- Use ONLY the data provided in the user message. Never invent numbers.
- If a specific figure is not in the provided data, say "data pending [field]" — do not fabricate.
- Write for a professional investor audience (buy-side / sell-side).
- Use INR (₹) currency notation. Use Indian numbering (Cr for crores, L for lakhs).
- Keep sections factual, specific, and citation-ready.
- Output only the section content — no headings, no meta-commentary.`;

// ─── LLM Section Generator ─────────────────────────────────────────────────────

async function generateSectionWithLLM(
  sectionName: string,
  prompt: string,
  apiKey?: string
): Promise<string | null> {
  console.log(`[SynthesisAgent] 📝 Synthesizing section '${sectionName}' via LLM...`);
  try {
    const { model, modelName } = await getModelForRequest(
      { provider: "groq", apiKey },
      prompt,
    );
    const response = await model.invoke([
      new SystemMessage(SYNTHESIS_SYSTEM_PROMPT),
      new HumanMessage(prompt),
    ]);
    const content = typeof response.content === "string" ? response.content : JSON.stringify(response.content);
    console.log(`[SynthesisAgent] ✓ Section '${sectionName}' generated using model '${modelName}'.`);
    return content.trim() || null;
  } catch (err) {
    console.error(`[SynthesisAgent] ❌ LLM generation failed for section "${sectionName}":`, err instanceof Error ? err.message : String(err));
    return null;
  }
}

// ─── Section prompt builders — inject real data, never defaults ───────────────

function buildExecutiveSummaryPrompt(input: SynthesisInput): string {
  const m = input.modelingData;
  const mi = input.marketIntelData;
  const valuation = m
    ? `Base-case target price: ₹${Math.round(m.baseTargetPrice)}/share (Bull: ₹${Math.round(m.bullCasePrice)}, Bear: ₹${Math.round(m.bearCasePrice)}).
       Model assumptions: ${JSON.stringify(m.assumptions)}.`
    : "Financial model output: not yet available.";

  const creditRating = mi?.creditRating ?? "not available";
  const peerBenchmark = mi?.benchmarkTableMarkdown
    ? `Peer benchmark summary:\n${mi.benchmarkTableMarkdown.slice(0, 600)}`
    : "Peer benchmark: not yet available.";

  return `Write an Executive Summary for ${input.companyName} (NSE: ${input.ticker}) for an institutional equity research initiation report.

Available data:
- ${valuation}
- Credit profile: ${creditRating}
- ${peerBenchmark}

The executive summary must:
1. State the investment rating and target price (if modeled).
2. Summarize the 3 most important investment thesis points supported by the data above.
3. Mention the DCF methodology and key assumptions if valuation data is available.
4. Be 150–200 words.`;
}

function buildBusinessDescriptionPrompt(input: SynthesisInput): string {
  const filingCount = input.documentData?.totalDocumentsFetched ?? (input.documentData?.filings ?? []).length;
  const filingTitles = input.documentData?.filingTitles ?? [];
  const isLiveFilings = input.documentData?.isLiveData ?? false;

  const filingsContext = filingTitles.length > 0
    ? `Actual exchange filings fetched (use these to describe business):\n` +
      filingTitles.slice(0, 10).map(f => `  - [${f.type}] ${f.title} (${f.date})`).join("\n")
    : filingCount > 0
    ? `${filingCount} exchange filings were fetched but filing content is not yet extracted. Describe general industry context only.`
    : `No exchange filings could be fetched. State clearly that "business details are unavailable from exchange filings" and describe general sector context only.`;

  return `Write the Business Description section for ${input.companyName} (NSE: ${input.ticker}).

Available data:
- Data is live from exchange: ${isLiveFilings}
- Total filings fetched: ${filingCount}
- ${filingsContext}

Critical rules:
1. Do NOT invent segment revenue splits or specific business unit percentages not in the data above.
2. If filing content is unavailable, explicitly state "Detailed segment data pending — based on exchange filing titles only."
3. Do not use your training data to fill in financial numbers. Only describe what business the company is in.
4. Be 120–150 words.`;
}

function buildFinancialAnalysisPrompt(input: SynthesisInput): string {
  const m = input.modelingData;
  if (!m) {
    return `Write a Financial Analysis placeholder for ${input.companyName} (${input.ticker}).
Note that the financial model has not yet been computed. State clearly that "financial model output is pending" 
and describe what will be covered in this section once the model runs (Revenue, EBITDA, PAT, ROCE).
Keep this to 80–100 words.`;
  }

  // Check if model used real data or fallback constants
  const isDerivedFromReal = m.assumptions?.isDerivedFromExtractedData === "True";
  const financialSource = m.assumptions?.financialSource ?? "unknown";
  const modelDisclaimer = m.assumptions?.disclaimer;

  const dataQualityNote = isDerivedFromReal
    ? `Model inputs sourced from: ${financialSource} (real financial data).`
    : `⚠️ IMPORTANT: Model used sector-average fallback constants (source: ${financialSource}) — actual financial data was unavailable. DO NOT present target price as research-grade. State this limitation clearly in the section.`;

  return `Write the Financial Analysis section for ${input.companyName} (NSE: ${input.ticker}).

DCF Model Output:
- Base-case target price: ₹${Math.round(m.baseTargetPrice)}/share
- Model assumptions: ${JSON.stringify(m.assumptions)}
- Projection type: ${m.modelType}
- Data quality: ${dataQualityNote}
${modelDisclaimer ? `- Model disclaimer: ${modelDisclaimer}` : ""}

Market intelligence:
- P/E Ratio: ${input.marketIntelData?.peRatio ?? "data pending"}
- Market Cap: ${input.marketIntelData?.marketCapCr ? `₹${input.marketIntelData.marketCapCr.toLocaleString()} Cr` : "data pending"}
- Promoter holding: ${input.marketIntelData?.promoterShareholding ? `${input.marketIntelData.promoterShareholding}%` : "data pending"}
- Screener live data: ${input.marketIntelData?.screenerIsLive ? "Yes" : "No — market multiples may be unavailable"}

Rules:
1. Summarize based ONLY on the above data.
2. ${isDerivedFromReal ? "Mention that model inputs were sourced from real exchange filings." : "You MUST include a clear disclaimer that the financial model used sector-average fallback constants, not actual audited financials. This is mandatory."}
3. Do not fabricate CAGR percentages or margin figures not present in the model output.
Be 150–180 words.`;
}

function buildValuationSectionPrompt(input: SynthesisInput): string {
  const m = input.modelingData;
  if (!m) {
    return `Write a Valuation section placeholder for ${input.companyName} (${input.ticker}).
State clearly that "valuation model output is pending completion of the financial model phase."
Keep this to 60 words.`;
  }

  const benchmarkTable = input.marketIntelData?.benchmarkTableMarkdown
    ? `\nPeer benchmark table:\n${input.marketIntelData.benchmarkTableMarkdown}`
    : "";

  return `Write the Valuation section for ${input.companyName} (NSE: ${input.ticker}).

Model results:
- Model type: ${m.modelType.toUpperCase()}
- Base case: ₹${Math.round(m.baseTargetPrice)}/share
- Bull case: ₹${Math.round(m.bullCasePrice)}/share
- Bear case: ₹${Math.round(m.bearCasePrice)}/share
- Assumptions: ${JSON.stringify(m.assumptions)}
${benchmarkTable}

Explain the valuation methodology and derive the target price from the model output above.
Present the bull/bear/base case scenarios. Reference peer multiples if the benchmark table is available.
Do not add assumptions not present in the data above.
Be 160–200 words.`;
}

function buildRisksSectionPrompt(input: SynthesisInput): string {
  const newsItems = input.marketIntelData?.newsItems ?? [];
  const newsContext = newsItems.length > 0
    ? `Recent news sentiment: ${newsItems.slice(0, 5).map(n => `"${n.title}" (${n.sentiment})`).join("; ")}`
    : "Recent news: not available.";

  return `Write the Key Risks section for ${input.companyName} (NSE: ${input.ticker}).

Context:
- Credit profile: ${input.marketIntelData?.creditRating ?? "data pending"}
- ${newsContext}

List 3–5 key investment risks specific to ${input.companyName}'s business and sector.
For each risk, provide a one-sentence mitigant.
Do not fabricate specific financial impact percentages — use qualitative risk language.
Be 150–180 words.`;
}

function buildConcallQASectionPrompt(input: SynthesisInput): string {
  // Prefer structured concall quotes from DocumentAgent
  const transcripts = input.concallTranscripts ?? [];
  const legacyQuotes = input.documentData?.concallQuotes ?? [];

  const allQuotes = transcripts.flatMap(t => t.quotes).slice(0, 8);

  if (allQuotes.length > 0) {
    const formatted = allQuotes
      .map(q => `[${q.quarter}] ${q.speakerRole}: "${q.quote}" — Topic: ${q.topic} (${q.sentiment})`)
      .join("\n");

    return `Synthesize the Management Q&A Highlights section for ${input.companyName} (${input.ticker}) using these earnings call quotes:

${formatted}

Summarize the key management messages, guidance, and tone. Group by topic (revenue guidance, margin, capex, risks).
Be 150–180 words. Do not add quotes or claims not in the above data.`;
  }

  if (legacyQuotes.length > 0) {
    const formatted = legacyQuotes
      .map(q => `${q.speaker ?? "Management"}: "${q.quote}"`)
      .join("\n");

    return `Synthesize the Management Q&A Highlights for ${input.companyName} from these quotes:\n\n${formatted}\n\nBe 120–150 words.`;
  }

  return `Write a Management Q&A Highlights placeholder for ${input.companyName} (${input.ticker}).
State clearly that "earnings call transcript data is pending — this section will be populated once concall transcripts are fetched from Screener.in."
Keep this to 50 words.`;
}

// ─── Synthesis Agent ──────────────────────────────────────────────────────────

export class SynthesisAgent {
  /**
   * Main entry point for Synthesis Subagent execution.
   * All section content is LLM-generated from real input data.
   * Data quality is tracked per-source and surfaced in output.dataSources.
   */
  public async run(input: SynthesisInput, apiKey?: string): Promise<SynthesisOutput> {
    const runId = input.runId ?? `synth_${Date.now()}`;
    const startTime = Date.now();

    // Build data source summary for logging and output
    const filingCount = input.documentData?.totalDocumentsFetched ?? (input.documentData?.filings ?? []).length;
    const concallQuoteCount = (input.concallTranscripts ?? []).flatMap(t => t.quotes).length;
    const isDerivedFromReal = input.modelingData?.assumptions?.isDerivedFromExtractedData === "True";
    const financialSource = input.modelingData?.assumptions?.financialSource ?? "sector_fallback";
    const newsCount = (input.marketIntelData?.newsItems ?? []).length;

    const dataSources: DataSourceSummary = {
      bseNseFilings: { count: filingCount, isLive: input.documentData?.isLiveData ?? filingCount > 0 },
      concallTranscript: { quotesFound: concallQuoteCount, isLive: concallQuoteCount > 0 },
      screenerMarketData: { isLive: input.marketIntelData?.screenerIsLive ?? false },
      creditRating: { isLive: input.marketIntelData?.creditRatingIsLive ?? false, found: !!input.marketIntelData?.creditRating && input.marketIntelData.creditRating !== "N/A" },
      news: { count: newsCount, isLive: input.marketIntelData?.newsIsLive ?? newsCount > 0 },
      dcfModel: { isDerivedFromRealData: isDerivedFromReal, source: financialSource },
    };

    console.log(`\n[SynthesisAgent] DATA SOURCES SUMMARY for ${input.companyName} (${input.ticker}):`);
    console.log(`[SynthesisAgent]   📄 Filings: ${filingCount} docs (${dataSources.bseNseFilings.isLive ? "🟢 live" : "🔴 none fetched"})`);
    console.log(`[SynthesisAgent]   🎙️  Concall: ${concallQuoteCount} quotes (${dataSources.concallTranscript.isLive ? "🟢 live" : "🔴 none"})`);
    console.log(`[SynthesisAgent]   📊 Screener: ${dataSources.screenerMarketData.isLive ? "🟢 live" : "🔴 failed"}`);
    console.log(`[SynthesisAgent]   🏦 Credit Rating: ${dataSources.creditRating.found ? "🟢 found" : "🔴 not found"} (${dataSources.creditRating.isLive ? "live" : "empty"})`);
    console.log(`[SynthesisAgent]   📰 News: ${newsCount} articles (${dataSources.news.isLive ? "🟢 live" : "🔴 none"})`);
    console.log(`[SynthesisAgent]   💹 DCF Model: ${isDerivedFromReal ? "🟢 REAL DATA" : "🔴 SECTOR FALLBACK"} (source: ${financialSource})`);
    if (!isDerivedFromReal) {
      console.warn(`[SynthesisAgent] ⚠️⚠️ DCF model used fallback constants — target price is UNRELIABLE.`);
    }

    trajectoryBus.emitEvent(
      input.planId,
      "subagent_start",
      { agent: "synthesis", summary: `Synthesizing report sections for ${input.companyName} (${input.ticker}) using live research data...` }
    );

    // Generate all sections via LLM, sequentially to respect rate limits
    const sectionDefs: { name: ReportSectionName; promptFn: () => string; citationsHint: string[] }[] = [
      {
        name: "executive_summary",
        promptFn: () => buildExecutiveSummaryPrompt(input),
        citationsHint: ["bse_filings", "dcf_model", "screener_market_intel"],
      },
      {
        name: "business_description",
        promptFn: () => buildBusinessDescriptionPrompt(input),
        citationsHint: ["annual_report"],
      },
      {
        name: "financial_analysis",
        promptFn: () => buildFinancialAnalysisPrompt(input),
        citationsHint: ["screener_financials", "dcf_model"],
      },
      {
        name: "valuation",
        promptFn: () => buildValuationSectionPrompt(input),
        citationsHint: ["dcf_model", "screener_peer_multiples"],
      },
      {
        name: "key_risks",
        promptFn: () => buildRisksSectionPrompt(input),
        citationsHint: ["sector_news", "credit_rating"],
      },
      {
        name: "management_qa_highlights",
        promptFn: () => buildConcallQASectionPrompt(input),
        citationsHint: ["concall_transcript"],
      },
    ];

    const sections: ReportSection[] = [];

    for (const def of sectionDefs) {
      const prompt = def.promptFn();
      const content =
        (await generateSectionWithLLM(def.name, prompt, apiKey)) ??
        `[${def.name} — data pending: LLM generation unavailable. ` +
        `Please ensure an API key is configured and retry.]`;

      const section: ReportSection = {
        name: def.name,
        content,
        citations: def.citationsHint,
        lastUpdatedAt: new Date().toISOString(),
        agentConfidence: content.includes("data pending") ? 0.2 : 0.85,
      };

      sections.push(section);
      SectionStore.saveSectionVersion(input.planId, section.name, section.content, section.citations);
      trajectoryBus.emitEvent(input.planId, "draft_updated", {
        sectionName: def.name,
        preview: content.slice(0, 120) + "…",
      });
    }

    // Run consistency check on executive summary vs modeling output
    const consistencyCheck = ConsistencyCheckerTool.checkSectionConsistency(
      "executive_summary",
      sections.find(s => s.name === "executive_summary")?.content ?? "",
      input.modelingData,
      undefined,
    );

    trajectoryBus.emitEvent(
      input.planId,
      "milestone_done",
      {
        milestoneRef: "synthesise",
        summary: `Synthesized ${sections.length} sections for ${input.companyName}. Consistency Score: ${(consistencyCheck.score * 100).toFixed(0)}%`,
      },
      "synthesise"
    );

    // DB record update (graceful for offline/demo tests)
    const runExists = await prisma.subagentRun.findUnique({ where: { id: runId } }).catch(() => null);
    if (runExists) {
      await prisma.subagentRun.update({
        where: { id: runId },
        data: {
          status: "completed",
          outputJson: { sections, consistencyCheck } as unknown as import("@prisma/client").Prisma.JsonObject,
          latencyMs: Date.now() - startTime,
        },
      }).catch(() => {});
    }

    return {
      runId,
      planId: input.planId,
      ticker: input.ticker,
      companyName: input.companyName,
      sections,
      consistencyCheck,
      dataSources,
      completedAt: new Date().toISOString(),
    };
  }
}

export const synthesisAgent = new SynthesisAgent();
